name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Tidy Go modules
      run: go mod tidy

    - name: Build binaries
      run: |
        GOOS=linux GOARCH=amd64 go build -o gher ./cmd/
        GOOS=windows GOARCH=amd64 go build -o gher.exe ./cmd/

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          gher
          gher.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
