name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build binaries
      run: |
        GOOS=linux GOARCH=amd64 go build -o ghershon
        GOOS=windows GOARCH=amd64 go build -o ghershon.exe

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ghershon
          ghershon.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
